[package]
name = "augurs-ets"
version = "0.1.0"
edition = "2021"

[dependencies]
augurs-core.workspace = true
augurs-mstl = { workspace = true, optional = true }
distrs.workspace = true
itertools = "0.10.5"
lstsq = "0.5.0"
nalgebra = "0.32.2"
rand = "0.8.0"
rand_distr = "0.4.3"
roots = "0.0.8"
serde = { version = "1.0.130", optional = true, features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"

[features]
mstl = ["dep:augurs-mstl"]
serde = ["dep:serde"]

[dev-dependencies]
assert_approx_eq.workspace = true
augurs-testing.workspace = true
criterion.workspace = true
pprof.workspace = true

[[bench]]
name = "air_passengers"
harness = false
